version: "2"
run:
  build-tags:
    - development
linters:
  default: all
  disable:
    - depguard
    - embeddedstructfieldcheck
    - err113 # TODO
    - exhaustruct
    - exhaustruct_v5
    # - godot # TODO
    # - godox # TODO
    - gomodguard # deprecated by v2
    - musttag # TODO
    - noinlineerr # we want inline errs, why not?
    - nonamedreturns # we want named returns
    - paralleltest # TODO
    - tagliatelle # legacy API, we don't control most of the APIs output.
    - testpackage # TODO
    - wrapcheck # TODO
    - wsl # deprecated by v5
  settings:
    cyclop:
      max-complexity: 35 # TODO: reduce
      package-average: 8 # TODO: reduce
    decorder:
      disable-dec-num-check: true
      disable-dec-order-check: false
    errcheck:
      #severity: warn
      disable-default-exclusions: false
      check-type-assertions: true
      check-blank: true
    errchkjson:
      #severity: Warn
      report-no-exported: true
    errorlint:
      asserts: true
    exhaustive:
      check:
        - switch
        - map
      default-signifies-exhaustive: true
    forbidigo:
      forbid:
        - pattern: "context.Background"
          msg: "Use t.Context() in tests instead of context.Background()"
        - pattern: "context.TODO"
          msg: "Use t.Context() in tests instead of context.TODO()"
    funlen:
      lines: 800 # TODO: reduce
      statements: 384 # TODO: reduce
      ignore-comments: true
    gocognit:
      min-complexity: 603 # TODO: reduce
    goconst:
      min-occurrences: 6
    gocritic:
      disabled-checks:
        - commentFormatting
        - exposedSyncMutex
        - commentedOutCode
      enabled-tags:
        - diagnostic
        - style
        - performance
        - experimental
        - opinionated
      settings:
        captLocal:
          paramsOnly: false
        elseif:
          skipBalanced: true
        hugeParam:
          sizeThreshold: 2265 # TODO: reduce
        nestingReduce:
          bodyWidth: 5
        rangeExprCopy:
          sizeThreshold: 512
          skipTestFuncs: true
        rangeValCopy:
          sizeThreshold: 201
          skipTestFuncs: true
        truncateCmp:
          skipArchDependent: true
        underef:
          skipRecvDeref: true
    gocyclo:
      min-complexity: 235 # TODO: reduce
    godot:
      scope: all
      exclude:
        - ^ HAS_.*
        - ^ \[.*\]$
      capital: true
    gosec:
      config:
        G302: "0640"
        G306: "0640"
      excludes:
        - G115 # TODO: panics on Go 1.26 until gosec is updated
    govet:
      enable-all: true
      settings:
        shadow:
          strict: true
    ireturn:
      allow:
        - empty
        - error
        - stdlib
        - generic
    lll:
      line-length: 196 # TODO: reduce
      tab-width: 1
    maintidx:
      under: 18 # TODO: bring it back to 20
    makezero:
      always: false
    mnd:
      ignored-numbers: ["2"]
    nakedret:
      max-func-lines: 120 # TODO: reduce
    nestif:
      min-complexity: 5
    nlreturn:
      block-size: 2
    nolintlint:
      require-explanation: true
      require-specific: true
      allow-unused: false
    prealloc:
      simple: true
      range-loops: true
      for-loops: false
    predeclared:
      qualified-name: false
    revive:
      rules:
        - name: exported
          disabled: true # TODO: enable
    testpackage:
      skip-regexp: (export|internal)_test\.go
    thelper:
      test:
        first: true
        name: true
        begin: true
      benchmark:
        first: true
        name: true
        begin: true
      tb:
        first: true
        name: true
        begin: true
    unparam:
      check-exported: true
    unused:
      field-writes-are-uses: true
      post-statements-are-reads: false
      exported-fields-are-used: false
      parameters-are-used: true
      local-variables-are-used: false
      generated-is-used: false
    varnamelen:
      max-distance: 25
      min-name-length: 2
      check-receiver: false
      check-return: true
      check-type-param: true
      ignore-names:
        - err
        - db
        - t0
        - t1
        - t2
        - tc
        - T
      ignore-type-assert-ok: true
      ignore-map-index-ok: true
      ignore-chan-recv-ok: true
      ignore-decls:
        - i int
        - i uint32
        - j int
        - t testing.T
        - b testing.B
        - T any
        - f *os.File
        - g *errgroup.Group
        - wg syng.WaitGroup
        - w http.ResponseWriter
        - r *http.Request
        - u auth.UserResp
        - u *auth.UserResp
        - u UserResp
        - u UserIdent
        - u auth.UserIdent
        - u *UserResp
        - q dynamodb.QueryInput
        - b expression.Builder
        - t time.Time
    wsl:
      strict-append: true
      allow-assign-and-call: true
      allow-multiline-assign: true
      force-case-trailing-whitespace: 0
      allow-trailing-comment: false
      allow-separated-leading-comment: false
      allow-cuddle-declarations: false
      force-err-cuddling: false
  exclusions:
    warn-unused: true
    generated: strict
    rules:
      - linters:
          - forbidigo
        text: Use t.Context
        path-except: _test\.go
      - linters:
          - goconst
          - gosec
          - govet
          - varnamelen
        path: _test\.go
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  new: false
  fix: false
formatters:
  enable:
    - gofmt
    - gofumpt
    - goimports
  settings:
    gofmt:
      simplify: true
    gofumpt:
      extra:
        group-params: true
        clothe-returns: false
        balance-calls: true
    goimports:
      local-prefixes: []
output:
  show-stats: true
