language: go
go:
  - 1.3.3
script: make test
install:
  - go get code.google.com/p/go.tools/cmd/cover
  - go get github.com/alexaandru/utils
  - go get launchpad.net/goamz/aws
  - go get launchpad.net/goamz/s3
