name: Auto-Release

on:
  push:
    tags: [v*]

permissions:
  contents: write

jobs:
  Release:
    runs-on: ubuntu-latest
    steps:
      - name: Create release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref_name }}
        run: |
          gh release create "${tag}" --title "${tag#v}" \
            --repo="${GITHUB_REPOSITORY}" --generate-notes
